"File: PNG/JPG":
- '**/*.png/*.jpg'

"File: MOV/MP4":
- '**/*.mp4/*.mov'

"File: Audio":
- '**/*.mp3/*.off
- 'Server content/Resources/Audio/**'

"File: Text":
- '**/*.txt/'

"File: Textures":
- 'Server content/Resources/Textures/**'

"File: github":
- '.github/**'

"Status: Needs Review":
- '**'
