"File: Picture":
- '**/*.png'
- '**/*.jpg'

"File: Video":
- '**/*.mp4'
- '**/*.mov'

"File: Audio":
- '**/*.mp3'
- '**/*.ogg'
- 'Server content/Resources/Audio/**'

"File: Text":
- '**/*.txt'

"File: Textures":
- 'Server content/Resources/Textures/**'
- '**/meta.json'

"File: github":
- '.github/**'

"Status: Needs Review":
- 'Server content/**'
- '.github/**'
- 'INFO/**'
- 'other/**'
