contact_links:
  - name: Идея
    url: https://discord.gg/sbsmPNXSbs
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить о проблеме
    url: https://discord.gg/sbsmPNXSbs
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности fedKotikeD#0001 (869137404735410216) в Discord.
